version: '3.4'

services:

    postgresql-base:
        container_name: '${PROJECT_NAME}-database'
        networks:
          main:
            ipv4_address: '${DB_HOST}'
        ports:
            - '${DB_PORT}:5432'
        volumes:
            - './data/:/var/lib/postgresql/data'
        environment:
            POSTGRES_DB: ${DB_NAME}
            PGUSER: ${DB_USER}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}", "-h", "localhost", "-p", "5432"]
            interval: 1s
            retries: 60
        image: postgres


    django-base:
        container_name: '${PROJECT_NAME}-server'
        depends_on:
            postgresql-base:
                condition: service_healthy
        networks:
          main:
            ipv4_address: '${SERVER_HOST}'
        ports:
            - '${SERVER_PORT}:8000'
        volumes:
            - './backend/:/usr/src/app/'
        environment:
            DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
            DB_ENGINE: ${DB_ENGINE}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            SERVER_HOST: ${SERVER_HOST}
            CLIENT_HOST: ${CLIENT_HOST}
            STATIC_ROOT: /usr/src/app/static/
        command: "daphne ${PROJECT_NAME}.asgi:application -b ${SERVER_HOST} -p ${SERVER_PORT}"
        build: docker/django/


    react-vite-base:
        container_name: '${PROJECT_NAME}-client'
        depends_on:
            - django-base
        networks:
          main:
            ipv4_address: '${CLIENT_HOST}'
        ports:
            - '${CLIENT_PORT}:5173'
        volumes:
            - './frontend/src/:/app/src'
            - './frontend/media/:/app/media'
            - './frontend/index.html:/app/index.html'
        build: docker/react-vite/


networks:
  main:
    driver: ${NETWORK_DRIVER}
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}
