version: '3.4'

services:
    react-vite-base:
        container_name: rolegm-client
        networks:
          main:
            ipv4_address: 172.18.0.3
        ports:
            - '5173:5173'
        volumes:
            - './frontend/:/app'
        build: docker/react-vite/
    django-base:
        container_name: rolegm-server
        networks:
          main:
            ipv4_address: 172.18.0.2
        ports:
            - '8000:8000'
        volumes:
            - './backend/:/usr/src/app/'
        build: docker/django/
networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
