version: '3.4'

services:

    postgresql-base:
        container_name: '${PROJECT_NAME}-database'
        networks:
          main:
            ipv4_address: '${DB_HOST}'
        ports:
            - '${DB_PORT}:5432'
        volumes:
            - './data/:/var/lib/postgresql/data'
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        image: postgres


    django-base:
        container_name: '${PROJECT_NAME}-server'
        depends_on:
            - postgresql-base
        networks:
          main:
            ipv4_address: '${SERVER_HOST}'
        ports:
            - '${SERVER_PORT}:8000'
        volumes:
            - './backend/:/usr/src/app/'
        environment:
            DB_ENGINE: ${DB_ENGINE}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            SERVER_HOST: ${SERVER_HOST}
            CLIENT_HOST: ${CLIENT_HOST}
        build: docker/django/


    react-vite-base:
        container_name: '${PROJECT_NAME}-client'
        depends_on:
            - django-base
        networks:
          main:
            ipv4_address: '${CLIENT_HOST}'
        ports:
            - '${CLIENT_PORT}:5173'
        volumes:
            - './frontend/:/app'
            - '/app/node_modules'
        build: docker/react-vite/


networks:
  main:
    driver: ${NETWORK_DRIVER}
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}
