# Generated by Django 4.0.8 on 2023-04-15 09:32

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(upload_to=core.models.Image.get_upload_path),
        ),
    ]
