# Generated by Django 4.0.8 on 2023-04-18 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_room_root_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='root_directory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.directory'),
        ),
    ]
