# Generated by Django 4.0.8 on 2023-04-15 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_audio_directory_alter_image_directory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.directory'),
        ),
        migrations.AlterField(
            model_name='image',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.directory'),
        ),
        migrations.AlterField(
            model_name='other',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.directory'),
        ),
    ]
