# Generated by Django 4.0.8 on 2023-04-15 10:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_audio_directory_alter_image_directory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='path',
            field=models.FileField(upload_to=core.models.Audio.get_upload_path),
        ),
        migrations.AlterField(
            model_name='other',
            name='path',
            field=models.FileField(upload_to=core.models.Other.get_upload_path),
        ),
    ]
