# Generated by Django 4.0.8 on 2023-04-18 06:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_player_room'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user', 'room')},
        ),
    ]
