# Generated by Django 4.0.8 on 2023-04-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_audio_path_alter_other_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='path',
            field=models.FileField(upload_to='media/audio-files'),
        ),
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(upload_to='media/image-files'),
        ),
        migrations.AlterField(
            model_name='other',
            name='path',
            field=models.FileField(upload_to='media/other-files'),
        ),
    ]
