# Generated by Django 4.0.8 on 2023-04-18 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_player_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.canvas')),
            ],
        ),
        migrations.AddField(
            model_name='canvas',
            name='active_page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_for', to='core.page'),
        ),
        migrations.AddField(
            model_name='canvas',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canvas', to='core.room'),
        ),
    ]
