# Generated by Django 4.0.8 on 2023-04-18 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_canvas_page_canvas_active_page_canvas_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='active_page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_for', to='core.page'),
        ),
    ]
