# Generated by Django 4.0.8 on 2023-04-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_canvas_active_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
