# Generated by Django 4.0.8 on 2023-04-17 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.directory'),
        ),
        migrations.AlterField(
            model_name='image',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.directory'),
        ),
        migrations.AlterField(
            model_name='other',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.directory'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
