# Generated by Django 4.0.8 on 2023-04-19 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_room_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='core.directory'),
        ),
        migrations.AlterField(
            model_name='image',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.directory'),
        ),
        migrations.AlterField(
            model_name='other',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='others', to='core.directory'),
        ),
    ]
